### ISSUE TITLE
TypeError: Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by pioneer** [sidneys/pb-for-desktop#110]
## 🤷🏽‍♂️ Current Behaviour

The error below happens when I try to run PB for Desktop.
```
[pioneer@hydrargyrum-vm-manjaro PB for Desktop]$ ./pb-for-desktop
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'includes' of undefined
    at Object.<anonymous> (/opt/PB for Desktop/resources/app.asar/app/scripts/main/components/application.js:84:35)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Object.<anonymous> (/opt/PB for Desktop/resources/electron.asar/browser/init.js:181:12)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
```

## 🎯 Expected Behaviour

The app should run without an error.

## 👟 Steps to Reproduce (S2R)

 1. Install the app
 2. Run it in the console

## 🏡 Environmental Context

**App Version**
v9.5.0
**Installation Type** 
An install from a fixed PKGBUILD, as the one in AUR is outdated.
**Operating System**
Manjaro Cinnamon

## Suggested solution
As a quick workaround, setting the `XDG_DATA_DIRS=/usr/local/share/:/usr/share/` to the default value suggested [here](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) works for me. I'd suggest adding a check for `undefined` for the `XDG_DATA_DIRS`variable (and maybe some other variables too), in the `application.js` file, line 85 which raises the exception.

**Comment by sidneys** [comment]
@pioneer Thanks for the report. Please re-test whether this issue still occurs in the new version (10.0.1).
