### ISSUE TITLE
electronBuilder: finally is not a function

### ISSUE THREAD

**Issue by harjoc** [sidneys/pb-for-desktop#119]
## 🤷🏽‍♂️ Current Behaviour

`npm run build` results in this error:
```
node_modules/@sidneys/electron-build/lib/build.js:47
            .finally(() => {
                    ^
TypeError: electronBuilder.build(...).then(...).catch(...).finally is not a function
```

## 👟 Steps to Reproduce (S2R)

Run `npm run build`.

## 🏡 Environmental Context

pb-for-desktop v10.5.0 cloned from github.
ubuntu 18.04.3
sidneys/electron-build@1.122.0
nodejs v8.10.0
npm 3.5.2

**Comment by harjoc** [comment]
Upgraded to nodejs 10 from nodesource APT repo, now I get:
```
  • building        target=pacman arch=x64 file=build/output/pb-for-desktop-10.5.0-x64.pacman
  ⨯ cannot execute  cause=exit status 1
                    out={:timestamp=>"2020-02-04T15:41:58.544608+0200", :message=>"Process failed: /bin/bash failed (exit code 127). Full command was:[\"/bin/bash\", \"-c\", \"LANG=C bsdtar -czf .MTREE --format=mtree --options='!all,use-set,type,uid,gid,mode,time,size,md5,sha256,link' .PKGINFO opt usr .INSTALL\"]", :level=>:error}
```
After `apt install bsdtar rpmbuild` I get:
```
  • building        target=deb arch=x64 file=build/output/pb-for-desktop-10.5.0-amd64.deb
  • building        target=pacman arch=x64 file=build/output/pb-for-desktop-10.5.0-x64.pacman
  • building        target=rpm arch=x64 file=build/output/pb-for-desktop-10.5.0-x86_64.rpm
{ Error: /home/bogdan/build/pb-for-desktop/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
    at ChildProcess.childProcess.once.code (/home/bogdan/build/pb-for-desktop/node_modules/builder-util/src/util.ts:239:14)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  exitCode: 1,
  alreadyLogged: false,
  code: 'ERR_ELECTRON_BUILDER_CANNOT_EXECUTE' }
```

**Comment by sidneys** [comment]
@harjoc 

Thank you for your report.

The [npm module](https://www.npmjs.com/package/pb-for-desktop) and all related dependencies have been deployed to match the [latest release](https://github.com/sidneys/pb-for-desktop/releases), which should solve this issue.

Please review and file an issue accordingly if the problem should reoccur.

Kind regards
S
