### ISSUE TITLE
Error the first time it's ran

### ISSUE THREAD

**Issue by hotice** [sidneys/pb-for-desktop#40]
Using PB For Desktop 5.0.0 in Ubuntu 16.10 (64bit), the application displays an error the first time it's ran:

```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'split' of undefined
    at cmp (/opt/PB for Desktop/resources/app.asar/node_modules/semver-compare/index.js:3:15)
    at bumpInternalVersion (/opt/PB for Desktop/resources/app.asar/app/scripts/main/services/updater-service.js:185:96)
    at init (/opt/PB for Desktop/resources/app.asar/app/scripts/main/services/updater-service.js:244:5)
    at App.app.once (/opt/PB for Desktop/resources/app.asar/app/scripts/main/services/updater-service.js:254:5)
    at Object.onceWrapper (events.js:290:19)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
```

It appears this is because the ~/.config/PB for Desktop/Settings file doesn't exist initially. Here's the console output:
```
$ pb-for-desktop 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/home/andrei/.config/PB for Desktop/Settings'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1233:33)
    at Object.writeFileSync (/opt/PB for Desktop/resources/app.asar/node_modules/jsonfile/index.js:115:13)
    at Settings._ensureSettings (/opt/PB for Desktop/resources/app.asar/node_modules/electron-settings/lib/settings.js:132:12)
    at Settings._readSettings (/opt/PB for Desktop/resources/app.asar/node_modules/electron-settings/lib/settings.js:171:10)
    at Settings._getValueAtKeyPath (/opt/PB for Desktop/resources/app.asar/node_modules/electron-settings/lib/settings.js:259:22)
    at Settings.getAll (/opt/PB for Desktop/resources/app.asar/node_modules/electron-settings/lib/settings.js:385:17)
    at setConfigurationDefaults (/opt/PB for Desktop/resources/app.asar/app/scripts/main/managers/configuration-manager.js:488:42)
    at App.app.once (/opt/PB for Desktop/resources/app.asar/app/scripts/main/managers/configuration-manager.js:552:5)
```

**Comment by sidneys** [comment]
@hotice Thanks. Please test with [v5.0.3.](../releases).

**Comment by hotice** [comment]
The issue no longer occurs, thanks!
