### ISSUE TITLE
A JavaScript error occurred in the main process Uncaught Exception.

### ISSUE THREAD

**Issue by riemannulus** [sidneys/pb-for-desktop#87]
## 🤷🏽‍♂️ Current Behaviour

When I executed from gnome-shell, it is nothing happened. however, printed some error message executed from terminal and do not executed.

## 🎯 Expected Behaviour

Want to use PB for Desktop in my laptop.

## 👟 Steps to Reproduce (S2R)

1. Download `pb-for-dektop-7.4.0.pacman`
2. execute from terminal `sudo pacman -U pb-for-desktop-7.4.0.pacman`
3. Successfully installed and launch in gnome-shell
4. nothing happened.
5. launch in terminal
6. get some error code below. 

```
suho@applejack ~ $ pb-for-desktop
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'includes' of undefined
    at Object.<anonymous> (/opt/PB for Desktop/resources/app.asar/app/scripts/main/components/application.js:61:35)
    at Object.<anonymous> (/opt/PB for Desktop/resources/app.asar/app/scripts/main/components/application.js:120:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Object.<anonymous> (/opt/PB for Desktop/resources/electron.asar/browser/init.js:186:8)
    at Object.<anonymous> (/opt/PB for Desktop/resources/electron.asar/browser/init.js:188:3)
    at Module._compile (module.js:642:30)
⚠️ [index.js] electron-updater-service init autoUpdater not supported on Linux 0.0314 ms
```

Actually, I'm not good at electron or JS. so, I don't know about this error message.
Is it bug? or just I missing something?

## 🏡 Environmental Context

**App Version**
v7.4.0
**Installation Type** 
`sudo pacman -U pb-for-desktop-7.4.0.pacman`
**Operating System**
Manjaro Linux (gnome) Kernel version 4.17-02

**Comment by riemannulus** [comment]
Same at https://github.com/sidneys/pb-for-desktop/issues/86
