### ISSUE TITLE
Fail to start 8.04 on Ubuntu 18.10 

### ISSUE THREAD

**Issue by jamtur01** [sidneys/pb-for-desktop#94]
## 🤷🏽‍♂️ Current Behaviour
Launching pb-for-desktop I see:

```
activating dev mode
activating dev mode
activating dev mode
activating dev mode
activating dev mode
activating dev mode
A JavaScript error occurred in the main process
Uncaught Exception:
RangeError: Maximum call stack size exceeded
at write (console.js:165:9)
at Console.log (console.js:197:3)
at crawl (/opt/PB for Desktop/resources/app.asar/node_modules/package.loader/lib/tools/crawler.js:47:13)
at crawl (/opt/PB for Desktop/resources/app.asar/node_modules/package.loader/lib/tools/crawler.js:49:5)
at crawl (/opt/PB for Desktop/resources/app.asar/node_modules/package.loader/lib/tools/crawler.js:49:5)
at crawl (/opt/PB for Desktop/resources/app.asar/node_modules/package.loader/lib/tools/crawler.js:49:5)
at crawl (/opt/PB for Desktop/resources/app.asar/node_modules/package.loader/lib/tools/crawler.js:49:5)
at crawl (/opt/PB for Desktop/resources/app.asar/node_modules/package.loader/lib/tools/crawler.js:49:5)
at crawl (/opt/PB for Desktop/resources/app.asar/node_modules/package.loader/lib/tools/crawler.js:49:5)
at crawl (/opt/PB for Desktop/resources/app.asar/node_modules/package.loader/lib/tools/crawler.js:49:5)
```

## 🎯 Expected Behaviour

Application starts normally.

## 👟 Steps to Reproduce (S2R)

1. Run the `pb-for-desktop` binary.

## 🏡 Environmental Context

**App Version**
v8.0.4
**Installation Type** 

Build from npm to a deb and installed.

**Operating System**

Ubuntu 18.10 (amd64) on Dell XPS 13 running under KDE Plasma.

**Comment by jtagcat** [comment]
I get just `Segmentation fault (core dumped)`

Ubuntu Budgie 18.10

**Comment by webNpro** [comment]
I have the same "Segmentation fault (core dumped)" problem. (Ubuntu 18.10)

**Comment by sidneys** [comment]
@jamtur01 

The current release has been tested on Ubuntu 18.10 and shouldn't demonstrate this behaviour any more.

Cheers, S

**Comment by jamtur01** [comment]
Thanks!
